version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tekvis_mongodata
    depends_on:
      - mongo
  mongo:
    container_name: tekvis_mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata:

